import java.awt.Dimension; 
import java.awt.Toolkit; 
import java.awt.event.KeyEvent; 
import java.sql.ResultSet; 
import java.sql.Statement; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 
import javax.swing.table.TableColumn;

public class frmDepartemen extends javax.swing.JFrame {
    //Membuat objek dari kelas clsDepartemen
    clsDepartemen objDep = new clsDepartemen();
    
    //Mendekalarasikan variabel
    private TableColumn column;
    
    /**
     * Creates new form frmDepartemen
     */
    public frmDepartemen() {
        initComponents();
        
        //Untuk mematikan tombol close
        setDefaultCloseOperation(frmDepartemen.DO_NOTHING_ON_CLOSE); 

        objDep.AksesData(); //koneksi ke database 
        IsiTabel(); //mengisi jTable dgn data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtDepartemen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Kode :");

        jLabel2.setText("Departemen :");

        txtKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKodeKeyTyped(evt);
            }
        });

        txtDepartemen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDepartemenKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDepartemenKeyTyped(evt);
            }
        });

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabel);

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        try 
	{ 
		BersihIsian(); 
		IsiTabel(); 
		txtKode.requestFocus(); 
	} 
	catch (Exception e) 
	{ 
	}
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        try 
	{ 
            objDep.Keluar(); 
            dispose(); 
	}
	catch (Exception e)
	{ 
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan"); 
            System.out.println(e.getMessage()); 
	}
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        //Panggil prosesdur simpan data 
        SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(txtKode.getText().equals("")||txtDepartemen.getText().equals(""))
	{
		JOptionPane.showMessageDialog(null,"Masukkan  departemen");
	}
	else
	{
            try
            {
		objDep.AksesData();
		objDep.KodeDep  =  txtKode.getText();
		objDep.NamaDep  =  txtDepartemen.getText();
		objDep.Edit(objDep.KodeDep,  objDep.NamaDep);
		objDep.res.executeUpdate(objDep.sql);
		objDep.conn.close();
		BersihIsian();
		IsiTabel();
		JOptionPane.showMessageDialog(null,"Data  berhasil  diupdate");
            }
            catch (Exception e) 
            { 
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/ koneksi gagal"); 
		System.out.println(e.getMessage()); 
            }
	}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try
	{
            objDep.AksesData();
            objDep.KodeDep  =  txtKode.getText();
            objDep.Hapus(objDep.KodeDep);
            objDep.res.executeUpdate(objDep.sql);
            objDep.conn.close();
            IsiTabel();
            BersihIsian();
            JOptionPane.showMessageDialog(null,"Data  berhasil  dihapus");
	}
	catch (Exception e) 
	{ 
            JOptionPane.showMessageDialog(null,"Proses penghapusan gagal/ koneksi gagal"); 
            System.out.println(e.getMessage()); 
	}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelMouseClicked
        // TODO add your handling code here:
        int  baris  =  jTabel.getSelectedRow();
	String  kolom1  =  jTabel.getValueAt(baris,  0).toString();
	String  kolom2  =  jTabel.getValueAt(baris,  1).toString();
	txtKode.setText(kolom1);
	txtDepartemen.setText(kolom2);
    }//GEN-LAST:event_jTabelMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
	//menampilkan  form  ditengah-tengah  layar
	Dimension  posisi  =  Toolkit.getDefaultToolkit().getScreenSize();
	int  x  =  (posisi.width  -  this.getWidth())/2;
	int  y  =  (posisi.height  -  this.getHeight())/2;
	this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

    private void txtKodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeKeyTyped
        // TODO add your handling code here:
        //untuk  membatasi  3  karakter
	if  (txtKode.getText().length()  >  2)
	evt.consume();
    }//GEN-LAST:event_txtKodeKeyTyped

    private void txtKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if ((txtKode.getText().length() < 3) || (txtKode.getText().isEmpty())) 
            { 
		JOptionPane.showMessageDialog(this, "Panjang kode harus 3 digit","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtKode.requestFocus(); 
            } 
            else 
            { 
		txtDepartemen.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtKodeKeyPressed

    private void txtDepartemenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepartemenKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if (txtDepartemen.getText().isEmpty()) 
            { 
                JOptionPane.showMessageDialog(this, "Masukkan nama departemen","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtDepartemen.requestFocus(); 
            } 
            else 
            { 
		btnSimpan.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtDepartemenKeyPressed

    private void txtDepartemenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepartemenKeyTyped
        // TODO add your handling code here:
	//untuk  membatasi  30  karakter
	if  (txtDepartemen.getText().length()  >  29)
	evt.consume();
    }//GEN-LAST:event_txtDepartemenKeyTyped

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
        //Memanggil  prosedur  simpand  ata
	SimpanData();
    }//GEN-LAST:event_btnSimpanKeyPressed

    //Prosedur membersihkan isian data 
    public void BersihIsian() 
    { 
	txtKode.setText(""); 
	txtDepartemen.setText(""); 
	txtKode.requestFocus(); 
    } 

    //Prosedur mengatur kolom jTable 
    private void AturKolom() 
    { 
	jTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        
	column = jTabel.getColumnModel().getColumn(0); 
	column.setPreferredWidth(80); 
	column = jTabel.getColumnModel().getColumn(1); 
	column.setPreferredWidth(320); 
    } 

    //Prosedur menampilkan data ke jTable 
    private void IsiTabel() 
    { 
	DefaultTableModel tabelmapel = new DefaultTableModel(); 
	
	tabelmapel.addColumn("Kode"); 
	tabelmapel.addColumn("Departemen"); 
	try 
	{ 
            objDep.AksesData(); 
            objDep.TampilData(); 
		
            Statement stat1 = objDep.conn.createStatement(); 
            ResultSet res1=stat1.executeQuery(objDep.sql); 
            while (res1.next()) 
            { 
                tabelmapel.addRow(new Object[]{res1.getString(1),res1.getString(2)}); 
            } 
            jTabel.setModel(tabelmapel); 
            AturKolom(); //atur kolom jTable 
	} 
	catch (Exception e) 
	{ 
	} 
    }
    
    private  void  SimpanData()
    {
	if(txtKode.getText().equals("")||txtDepartemen.getText().equals(""))
	{
            JOptionPane.showMessageDialog(null,"Data  harus  diisi  semua");
	}
	else
	{
            try
            {
                objDep.AksesData();
		objDep.KodeDep  =  txtKode.getText();
		objDep.NamaDep  =  txtDepartemen.getText();
		objDep.Simpan(objDep.KodeDep,  objDep.NamaDep);
		objDep.res.executeUpdate(objDep.sql);
		objDep.conn.close();
		BersihIsian();
		IsiTabel();
		JOptionPane.showMessageDialog(null,"Data  berhasil  disimpan");
            }
            catch (Exception e) 
            { 
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal"); 
		System.out.println(e.getMessage()); 
            } 
	} 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDepartemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDepartemen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField txtDepartemen;
    private javax.swing.JTextField txtKode;
    // End of variables declaration//GEN-END:variables
}
