//import  komponen
import  java.awt.Dimension;
import  java.awt.Toolkit;
import  java.awt.event.KeyEvent;
import  java.sql.ResultSet;
import  java.sql.Statement;
import  javax.swing.JOptionPane;
import  javax.swing.table.DefaultTableModel;
import  javax.swing.table.TableColumn;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guest_2
 */
public class frmKaryawan extends javax.swing.JFrame {

    //membuat  objek  dari  kelas  clsKaryawan
    clsKaryawan  objKaryawan  =  new  clsKaryawan();
    //Mendeklarasikan  variabel
    private  TableColumn  column;
    
    /**
     * Creates new form frmKaryawan
     */
    public frmKaryawan() {
        initComponents();
        //Untuk  mematikan  tombol  close
	setDefaultCloseOperation(frmDepartemen.DO_NOTHING_ON_CLOSE);
	//koneksi  ke  database
	objKaryawan.AksesData();
	IsiTabel();  //mengisi  jTable  dgn  data
	IsiComboDepartemen();  //memanggil  prosedur
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtGaji = new javax.swing.JTextField();
        cboDepartemen = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("NIK :");

        jLabel2.setText("Nama :");

        jLabel3.setText("Departemen :");

        jLabel4.setText("Gaji :");

        txtNIK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIKKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNIKKeyTyped(evt);
            }
        });

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        txtGaji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGajiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGajiKeyTyped(evt);
            }
        });

        cboDepartemen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDepartemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboDepartemenMouseClicked(evt);
            }
        });
        cboDepartemen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDepartemenKeyPressed(evt);
            }
        });

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabel);

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama)
                            .addComponent(cboDepartemen, 0, 140, Short.MAX_VALUE)
                            .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here: 
	try 
	{ 
            BersihIsian(); 
            IsiTabel(); 
            txtNIK.requestFocus(); 
	} 
	catch (Exception e) 
	{ 
	}
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(txtNIK.getText().equals("")) 
	{ 
            JOptionPane.showMessageDialog(null,"Pilih data yang diedit"); 
	}
	else 
	{ 
            try 
            { 
		objKaryawan.AksesData(); 
		objKaryawan.NIK = txtNIK.getText(); 
		objKaryawan.Nama = txtNama.getText(); 
		objKaryawan.KodeDep = cboDepartemen.getSelectedItem().toString().substring(0, 3); 
		String mGaji = txtGaji.getText(); 
		objKaryawan.Gaji = Integer.parseInt(mGaji); 
		objKaryawan.Edit(); 
		objKaryawan.res.executeUpdate(objKaryawan.sql); 
		objKaryawan.conn.close(); 
		BersihIsian(); 
		IsiTabel(); 
		JOptionPane.showMessageDialog(null,"Data berhasil diupdate"); 
            } 
            catch (Exception e) 
            { 
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal"); 
		System.out.println(e.getMessage()); 
            } 
	}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try 
	{ 
            objKaryawan.AksesData(); 
            objKaryawan.NIK = txtNIK.getText(); 
            objKaryawan.Hapus(objKaryawan.NIK); 
            objKaryawan.res.executeUpdate(objKaryawan.sql); 
            objKaryawan.conn.close(); 
            IsiTabel(); 
            BersihIsian(); 
            JOptionPane.showMessageDialog(null,"Data berhasil dihapus"); 
	} 
	catch (Exception e) 
	{ 
            JOptionPane.showMessageDialog(null,"Proses penghapusan gagal/koneksi gagal"); 
            System.out.println(e.getMessage()); 
	}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelMouseClicked
        // TODO add your handling code here:
        int baris = jTabel.getSelectedRow(); 
	String kolom1 = jTabel.getValueAt(baris, 0).toString(); 
	String kolom2 = jTabel.getValueAt(baris, 1).toString(); 
	String kolom3 = jTabel.getValueAt(baris, 2).toString() +" : "+ jTabel.getValueAt(baris, 3).toString(); 
	String kolom5 = jTabel.getValueAt(baris, 4).toString(); 
		
	txtNIK.setText(kolom1); 
	txtNama.setText(kolom2); 
	cboDepartemen.removeAllItems(); 
	cboDepartemen.addItem(kolom3);
	txtGaji.setText(kolom5);
    }//GEN-LAST:event_jTabelMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        try 
	{ 
            objKaryawan.Keluar(); 
            dispose(); 
	}
	catch (Exception e)
	{ 
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan"); 
            System.out.println(e.getMessage()); 
	}
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cboDepartemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboDepartemenMouseClicked
        // TODO add your handling code here:
        //Panggil prosedur isi dat adi combobox 
	IsiComboDepartemen();
    }//GEN-LAST:event_cboDepartemenMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //membuat posisi form ditengah layar 
	Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize(); 
	int x = (posisi.width - this.getWidth())/2; 
	int y = (posisi.height - this.getHeight())/2; 
	this.setLocation(x,y);
    }//GEN-LAST:event_formWindowActivated

    private void txtNIKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIKKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if ((txtNIK.getText().length() < 8) || (txtNIK.getText().isEmpty())) 
            { 
		JOptionPane.showMessageDialog(this, "Panjang NIK harus 8 digit","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtNIK.requestFocus(); 
            } 
            else 
            { 
                txtNama.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtNIKKeyPressed

    private void txtNIKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIKKeyTyped
        // TODO add your handling code here:
        //untuk membatasi 8 karakter 
	if (txtNIK.getText().length() > 7) 
	evt.consume();
    }//GEN-LAST:event_txtNIKKeyTyped

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if (txtNama.getText().isEmpty()) 
            {
		JOptionPane.showMessageDialog(this, "Nama harus diisi","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtNama.requestFocus(); 
            } 
            else 
            { 
		cboDepartemen.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtNamaKeyPressed

    private void cboDepartemenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDepartemenKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            txtGaji.requestFocus(); 
	}
    }//GEN-LAST:event_cboDepartemenKeyPressed

    private void txtGajiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGajiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) 
	{ 
            if (txtNIK.getText().isEmpty()) 
            { 
		JOptionPane.showMessageDialog(this, "Silahkan isi gaji","Informasi", 
		JOptionPane.INFORMATION_MESSAGE); 
		txtGaji.requestFocus(); 
            } 
            else 
            { 
		btnSimpan.requestFocus(); 
            } 
	}
    }//GEN-LAST:event_txtGajiKeyPressed

    private void txtGajiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGajiKeyTyped
        // TODO add your handling code here:
        //Panjang digit gaji 9 
	if (txtGaji.getText().length() > 8) 
	evt.consume(); 
		
	//hanya menerima input angka saja 
	char karakter = evt.getKeyChar(); 
	if (!(((karakter>='0') && (karakter <='9')||(karakter == KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))) 
	{ 
            getToolkit().beep(); 
            evt.consume(); 
	}
    }//GEN-LAST:event_txtGajiKeyTyped

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
        if (txtNama.getText().length() > 29) 
	evt.consume();
    }//GEN-LAST:event_txtNamaKeyTyped

    //prosedur simpan data 
    private void SimpanData() 
    { 
	if(txtNIK.getText().equals("")||txtNama.getText().equals("")) 
	{ 
            JOptionPane.showMessageDialog(null,"Data harus diisi semua"); 
	} 
	else 
	{ 
            try 
            { 
		objKaryawan.AksesData(); 
		objKaryawan.NIK = txtNIK.getText(); 
		objKaryawan.Nama = txtNama.getText(); 
		objKaryawan.KodeDep = cboDepartemen.getSelectedItem().toString().substring(0, 3); 
		String mGaji = txtGaji.getText(); 
		objKaryawan.Gaji = Integer.parseInt(mGaji); 
		objKaryawan.Simpan(); 
		
		objKaryawan.res.executeUpdate(objKaryawan.sql); 
		objKaryawan.conn.close(); 
		BersihIsian(); 
		IsiTabel(); 
		JOptionPane.showMessageDialog(null,"Data berhasil disimpan"); 
            } 
            catch (Exception e) 
            { 
		JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal"); 
		System.out.println(e.getMessage()); 
            } 
	} 
    }
        
    //Prosedur membersihkan isian data 
    public void BersihIsian() 
    { 
	txtNIK.setText(""); 
	txtNama.setText(""); 
	IsiComboDepartemen(); 
	txtGaji.setText(""); 
	txtNIK.requestFocus(); 
    }
	
    //prosedur mengatur kolom jTable 
    private void AturKolom() 
    { 
	jTabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
	column = jTabel.getColumnModel().getColumn(0); 
	column.setPreferredWidth(80); 
	column = jTabel.getColumnModel().getColumn(1); 
	column.setPreferredWidth(170); 
	column = jTabel.getColumnModel().getColumn(2); 
	column.setPreferredWidth(50); 
	column = jTabel.getColumnModel().getColumn(3); 
	column.setPreferredWidth(170); 
	column = jTabel.getColumnModel().getColumn(4); 
	column.setPreferredWidth(100); 
    }
	
    //Prosedur menampilkan data ke jTable 
    private void IsiTabel() 
    { 
	DefaultTableModel tabelmapel = new DefaultTableModel(); 
	
	tabelmapel.addColumn("NIK"); 
	tabelmapel.addColumn("Nama"); 
	tabelmapel.addColumn("Kode"); 
	tabelmapel.addColumn("Departemen"); 
	tabelmapel.addColumn("Gaji"); 
	try 
	{ 
            objKaryawan.AksesData(); 
            objKaryawan.TampilData(); 
			
            Statement stat1 = objKaryawan.conn.createStatement(); 
            ResultSet res1=stat1.executeQuery(objKaryawan.sql); 
            while (res1.next()) 
            { 
		tabelmapel.addRow(new Object[]{res1.getString(1),res1.getString(2),res1.getString(3),res1.getString(4),res1.getString(5)}); 
            } 
            jTabel.setModel(tabelmapel); 
            AturKolom(); //atur kolom jTable 
	} 
	catch (Exception e) 
	{ 
	} 
    }
	
    //prosedur mengisi combobox dengan data 
    public void IsiComboDepartemen() 
    { 
	try 
            { 
		cboDepartemen.removeAllItems(); 
		objKaryawan.AksesData(); 
		String sql1 = "select * from tbldepartemen"; 
		Statement stat1 = objKaryawan.conn.createStatement(); 
		ResultSet res1=stat1.executeQuery(sql1); 
		cboDepartemen.addItem("Pilih Departemen"); 
		while(res1.next()) 
            { 
		cboDepartemen.addItem(res1.getString("KodeDep") + " : " + res1.getString("NamaDep")); 
            } 
	} 
	catch(Exception e) 
	{
	} 
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cboDepartemen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
